# Generated by Django 5.1.2 on 2024-10-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
