# Generated by Django 5.1.2 on 2024-10-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='product',
            name='Features',
            field=models.TextField(blank=True, help_text='Store multiple descriptions separated by commas or newlines', null=True),
        ),
    ]
