# Generated by Django 5.1.2 on 2024-10-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_product_descriptions_product_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Features',
            new_name='features',
        ),
    ]
