# Generated by Django 5.1.2 on 2024-10-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_features_product_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Store multiple descriptions separated by newlines', null=True),
        ),
    ]
